/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sirshande.listaDeInformacion;

/**
 *
 * @author sirshande
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbRegistrar = new javax.swing.JButton();
        jtCodigo = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtSueldoNeto = new javax.swing.JTextField();
        jtVenta = new javax.swing.JTextField();
        jtNumHijos = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jtComision = new javax.swing.JTextField();
        jtSueldoBase = new javax.swing.JTextField();
        jtDescuentoImpuesto = new javax.swing.JTextField();
        jtEstadoCivil = new javax.swing.JTextField();
        jtDescuentos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(jtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, -1));
        getContentPane().add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, -1));
        getContentPane().add(jtSueldoNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, -1));
        getContentPane().add(jtVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));
        getContentPane().add(jtNumHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, -1));

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "CASADO", "VIUDO", "SOLTERO" }));
        getContentPane().add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, -1));
        getContentPane().add(jtComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, -1));
        getContentPane().add(jtSueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 160, -1));
        getContentPane().add(jtDescuentoImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 160, -1));
        getContentPane().add(jtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 170, -1));
        getContentPane().add(jtDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        // TODO add your handling code here:
        String codigo = jtCodigo.getText();
        String nombreCompleto = jtNombre.getText().toUpperCase();
        String estadoCivil = jcbEstado.getSelectedItem().toString();
        double sueldoBase = Double.parseDouble(jtSueldoBase.getText());
        double venta = Double.parseDouble(jtVenta.getText());
        int hijosNum = Integer.parseInt(jtNumHijos.getText());
        String estado = estadoCivil; // Usar el valor ya obtenido

        double comision = venta * 0.1;
        jtComision.setText(String.valueOf(comision));

        double par1 = sueldoBase + comision;
        double descuentoImpuesto = 0.0;

        if (par1 > 3000) {
            descuentoImpuesto = par1 * 0.06;
        } else if (par1 > 2300) {
            descuentoImpuesto = par1 * 0.04;
        } else if (par1 > 1500) {
            descuentoImpuesto = par1 * 0.03;
        }

        jtDescuentoImpuesto.setText(String.valueOf(descuentoImpuesto));

        double descuentos = 0.0;

        if (estado.equals("SOLTERO")) {
            descuentos = 100;
            jtEstadoCivil.setText("SOLTERO");
        } else if (estado.equals("CASADO")) {
            if (hijosNum != 0) {
                descuentos = 50 + (70 * hijosNum);
                jtEstadoCivil.setText("CASADO");
            } else {
                descuentos = 120;
                jtEstadoCivil.setText("SOLTERO");
            }
        }

        jtDescuentos.setText(String.valueOf(descuentos));

        double sueldoNeto = sueldoBase + comision - descuentoImpuesto - descuentos;
        jtSueldoNeto.setText(String.valueOf(sueldoNeto));

        

    }//GEN-LAST:event_jbRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtComision;
    private javax.swing.JTextField jtDescuentoImpuesto;
    private javax.swing.JTextField jtDescuentos;
    private javax.swing.JTextField jtEstadoCivil;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNumHijos;
    private javax.swing.JTextField jtSueldoBase;
    private javax.swing.JTextField jtSueldoNeto;
    private javax.swing.JTextField jtVenta;
    // End of variables declaration//GEN-END:variables
}
